version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo
    #   MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    # image: 'redislabs/redismod'
    container_name: redis
    build: .
    # command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  redis-data:
  mongodb_data: # run: docker volume create mongodb_data
    external: true
